version: "3"

services:
  mongoDB:
    image: "mongo:4"
    container_name: "app-mongo"
    volumes:
      - ../db:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - app-network
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: "app"
    ports:
      - "3000:3000"
    networks:
      - app-network
networks:
  app-network:
    external: true